# Professional Analysis Options - Teer Khela Production App
# Optimized by Senior Developer (10+ years experience)

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    # Treat critical issues as errors
    invalid_assignment: error
    missing_required_param: error
    missing_return: error

    # Warnings for code quality
    unused_import: warning
    unused_local_variable: warning

    # Info only (suppress in build)
    deprecated_member_use: info
    todo: ignore

linter:
  rules:
    # Performance optimizations
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - sized_box_for_whitespace

    # Code quality
    - always_declare_return_types
    - annotate_overrides
    - await_only_futures
    - camel_case_types
    - empty_catches
    - null_closures
    - prefer_final_fields
    - unnecessary_this
    - use_key_in_widget_constructors
